#!/bin/bash

# Usage: ./submit-csd3 --groups 65536 --seed 0 --samples 10 --nprocs 1 --walltime 1:00:00 --dir /path/to/run/dir

set -e
set -u

# Defaults
groups=65536
samples=10
seed=0
nprocs=1
walltime=1:00:00

while [ $# -gt 0 ]; do
    if [ $1 = "--groups" ]; then
        groups=$2
        shift 2
    elif [ $1 == "--seed" ]; then
        seed=$2
        shift 2
    elif [ $1 == "--samples" ]; then
        samples=$2
        shift 2
    elif [ $1 == "--dir" ]; then
        dir=$2
        shift 2
    elif [ $1 == "--nprocs" ]; then
        nprocs=$2
        shift 2
    elif [ $1 == "--walltime" ]; then
        walltime=$2
        shift 2
    else
        echo "Unrecognised arguments: $*" >&2
        exit 1
    fi
done

jobname=$(basename $dir)

mkdir $dir
cp -a ./analysis $dir

cat >$dir/submit.sh <<EOF
#!/bin/bash
#SBATCH --job-name $jobname
#SBATCH --account DIRAC-DC003-CPU
#SBATCH --ntasks $nprocs
#SBATCH --time $walltime
#SBATCH --mail-type ALL
#SBATCH --no-requeue
#SBATCH --partition skylake
#SBATCH --output log.txt

####################################################################
# Setup environment
####################################################################

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-peta4

####################################################################
# Run CoronaPMCMC
####################################################################

echo
echo "Running simulation"
echo "=================="
echo
./analysis $groups $seed

echo
echo "Running inference"
echo "================="
echo
#./analysis $groups $samples $seed

mpirun -n $nprocs ./analysis $groups $samples $seed

EOF

cd $dir
chmod u+x submit.sh
sbatch submit.sh
