description = "This analysis uses an SEIR model and assumes that the reproduction number R remains constant (i.e. the contact rate between individuals remains the same over time), as well as a constant external force of intection." 

time_format = "year-month-day"
start = "2020-01-01"
end = "2020-09-01"

datadir = "examples/Data_EX"
outputdir = "Output_EX"

comps = [
{name="S"},
{name="E", dist="Erlang", k="2", mean_value="4"},
{name="I", dist="Exp", mean_value="4", inf_value="1"},
{name="R"}
]

trans = [
{from="S", to="E", infection="yes"},
{from="E", to="I"},
{from="I", to="R"}
] 

R_spline = [{ value="2.0", prior="Uniform(0.4,4)"}]
efoi_spline = [{ value="0.1"}]

areas = "scotland.csv"

data_tables = [{type="transition", observation="E->I", timestep="7", file="EI.csv"}]

state_outputs = [
{plot_name="Dynamics", type="population", observation="S", line_colour="green"},
{plot_name="Dynamics", type="population", observation="E", line_colour="yellow"},
{plot_name="Dynamics", type="population", observation="I", line_colour="red"},
{plot_name="Dynamics", type="population", observation="R", line_colour="blue"}
]

modification = [{start="2020-04-01",type="beta_fac",factor="0.3"}]
