# Simulation: ./beepmbp inputfile="examples/EX3c.toml" mode="sim" 
# Inference: mpirun -n 20 ./beepmbp inputfile="examples/EX3c.toml" mode="ml" algorithm="cmaes" nsample_final=200   posterior_particle=200 nparticle=200 ngeneration=30 invT=1000

description = "This analysis uses an SIRD branching model with the population demographically stratified into males and females. The infected individuals can either recover or die with associated branching probabilities. The reproduction number R remains constant (i.e. the contact rate between individuals remains the same over time), as well as a constant external force of infection. Data consists of the weekly number of S->I cases and I->R deaths separately for males and females. The reproduction number and the sex-stratified infectious period and branching probabilities are inferred from this data." 

time_format = "number"
start = "0"
end = "140"

datadir = "examples/Data_EX3c"
outputdir = "analysis/Output_EX3c"

democats = [{name="Sex", cats="Male | Female"}] 

comps = [
{name="S"},
{name="I", dist="Exp", mean_value="Sex: 6 | 4", inf_value="1", mean_prior="Uniform(1,10)"},
{name="R"},
{name="D"}
]

trans = [
{from="S", to="I", infection="yes"},
{from="I", to="R", prob_value="Sex: 0.8 | 0.7", prob_prior="Dir(1)"},
{from="I", to="D", prob_value="Sex: *", prob_prior="Dir(1)"}
] 

R_spline = [{ value="2", prior="Uniform(0.5,4)"}]

efoi_spline = [{ value="1"}]

areas = "population.csv"

data_tables = [
{type="transition", observation="S->I", timestep="7", obsmodel="scale", democats_dep="Sex", file="S-I.csv"},
{type="transition", observation="I->D", timestep="7", obsmodel="scale", democats_dep="Sex", file="I-D.csv"},
]

state_outputs = [
{plot_name="Dynamics", type="population", observation="S", line_colour="green"},
{plot_name="Dynamics", type="population", observation="I", line_colour="red"},
{plot_name="Dynamics", type="population", observation="R", line_colour="blue"},
{plot_name="Dynamics", type="population", observation="D", line_colour="black"}
]

plot_param_values = "true"

