# Simulation: ./beepmbp inputfile="examples/EX5a.toml" mode="sim" 
# Inference: mpirun -n 20 ./beepmbp inputfile="examples/EX5a.toml" mode="ml" algorithm="cmaes" nsample_final=200   posterior_particle=200 nparticle=200 ngeneration=150 invT=10000

description = "A piecewise linear spline is used to represent time variation in the reproduction number R. An SIR model is assumed with a constant external force of infection. Data consists of the weekly number of S→I infections and I→R recoveries. The reproduction number spline (determined by a series of model parameters at specified time points) and infection period are inferred from this data." 

time_format = "number"
start = "0"
end = "518"

time_labels = [{name="Lockdown", time="30"},{name="Lockdown 2", time="252"},{name="Lockdown 3", time="336"}]

datadir = "examples/Data_EX5a"
outputdir = "analysis/Output_EX5a"

comps = [
{name="S"},
{name="I", dist="Exp", mean_value="14", inf_value="1", mean_prior="Uniform(10,20)"},
{name="R"}
]

trans = [
{from="S", to="I", infection="yes"},
{from="I", to="R"}
] 

R_spline = [{ param="[R:R_spline.csv]", value="[value:R_spline.csv]", prior="[prior:R_spline.csv]", bp="[bp:R_spline.csv]", smooth_type="log_smooth", smooth="[smooth:R_spline.csv]"}]

efoi_spline = [{ value="0.1"}]

areas = "population.csv"

data_tables = [
{type="transition", observation="S->I", timestep="7", obsmodel="scale", file="S-I.csv"},
{type="transition", observation="I->R", timestep="7", obsmodel="scale", file="I-R.csv"}
]

state_outputs = [
{plot_name="Dynamics", type="population", observation="S", line_colour="green"},
{plot_name="Dynamics", type="population", observation="I", line_colour="red"},
{plot_name="Dynamics", type="population", observation="R", line_colour="blue"}
]

plot_param_values = "true"

