# Simulation:
# build/bin/BEEP inputfile="examples/EX_A1.toml" mode="sim" 

# Below we show possible inference algorithms. MAP is found to be fastest and would be recommended

# Inference using MAP estimate: 
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="map"

# Inference using ABC-MBP:  
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="abcmbp" nparticle=200 ngeneration=10

# Inference using PAS-MBP:  
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="pas" nparticle=200 ngeneration=10

# Inference using ABC:  
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="abc" nsample=100 cutoff_frac=0.001 

# Inference using ABC-SMC:
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="abcsmc" ngeneration=6 nsample=200

# Inference using PMCMC:
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="pmcmc" nparticle=100 nsample=1000

# Inference using MCMC-MBP:
# mpirun -n 4 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="mcmcmbp" invT=1 nsample=1000 nrun=4

# Inference using MC3:
# mpirun -n 20 build/bin/BEEP inputfile="examples/EX_A1.toml" mode="mc3" nchain=20 invT_final=1 nsample=1000 


description = "Objective: Introduce a simple epidemiological model to illustrate simulation and inference.  Implementation: ‘comps’ defines the compartments in the model and ‘trans’ the transitions. ‘R-spline’ and ‘efoi-spline’ define the time variation in reproduction number R_t and external force of infection η_t (both of which are assumed to remain fixed in this example). ‘areas’ references a file giving information about the overall population (in this case 10,000 individuals intermixing in a single area). ‘data-tables’ references files giving the weekly number of infections and recoveries.  Model: This model contains three compartments: susceptible (S), infected (I) and recovered (R). Together they are known as the “SIR model”. The reproduction number R_t measures the number of secondary infections from an initially infected individual, in an otherwise susceptible population (note, the effective reproduction number also accounts for the reduction in the susceptible population over time, and this is a model output). The value of R_t is proportional to the rate at which individuals come into contact (with each contact allowing for the possibility of disease transmission). This model assumes that R_t remains constant, and hence the contact rate between individuals remains the same over time. Furthermore, a constant external force of infection is assumed.  Data: The weekly number of S->I infections and I->R recoveries.  Inference: The reproduction number R_t and infection period." 

time_format = "number"
start = "0"
end = "140"

datadir = "examples/Data_EX_A1"
outputdir = "examples/Output_EX_A1"

comps = [
{name="S"},
{name="I", dist="Exp", mean_value="6", inf_value="1", mean_prior="Uniform(1,10)"},
{name="R"}
]

trans = [
{from="S", to="I", infection="yes"},
{from="I", to="R"}
] 

R_spline = [{ value="2", prior="Uniform(0.5,4)"}]

efoi_spline = [{ value="0.1"}]

areas = "population.csv"

data_tables = [
{type="transition", observation="S->I", timestep="7", obsmodel="normal 10%", file="S-I.csv"},
{type="transition", observation="I->R", timestep="7", obsmodel="normal 10%", file="I-R.csv"}
]

state_outputs = [
{plot_name="Dynamics", type="population", observation="S", line_colour="green"},
{plot_name="Dynamics", type="population", observation="I", line_colour="red"},
{plot_name="Dynamics", type="population", observation="R", line_colour="blue"}
]

plot_param_values = "true"

