# Simulation:
# build/bin/BEEPmbp inputfile="examples/EX_F5.toml" mode="multisim" nsimulation="400"

description = "Objective: Simulating from a model multiple times using the same set of parameters allows the user to see how inherently stochastic the system is (in general stochasticity will tend to be less for larger population sizes, although it can still be important when the number of infected individuals is small early on in an epidemic).  Implementation: Multiple simulations can be carried out using the “multisim” mode. Opening “visBEEPmbp.html” and going to the “Multisim→State Output” tab on the menu we see the inherent variation in the number of weekly cases (here the red dashed lines bound 95% of simulated outcomes). We find the simulated dataset (denoted by the solid black lines) lies within these bounds.  Model: An SEIR model with constant reproduction number R_t (i.e. the contact rate between individuals remains the same over time), as well as a constant external force of infection.  Data: Weekly number of E→I cases and measurements on the total infected I and recovered R populations.  Multiple simulation: The variation is state over multiple simulations from the same parameter values." 

time_format = "number"
start = "0"
end = "140"

datadir = "examples/Data_EX_F5"
outputdir = "examples/Output_EX_F5"  
comps = [
{name="S"},
{name="E", dist="Erlang", k="2", mean_value="3", mean_prior="Uniform(1,10)"},
{name="I", dist="Exp", mean_value="4", inf_value="1", mean_prior="Uniform(1,10)"},
{name="R"}
]

trans = [
{from="S", to="E", infection="yes"},
{from="E", to="I"},
{from="I", to="R"}
] 

R_spline = [{ value="2", prior="Uniform(0.5,4)"}]

efoi_spline = [{ value="0.5"}]

areas = "population.csv"

data_tables = [
{type="transition", observation="E->I", timestep="7", obsmodel="normal 10%", file="E-I.csv"},
{type="population", observation="I", timestep="7", obsmodel="normal 10%", file="I.csv"},
{type="population", observation="R", timestep="7", obsmodel="normal 10%", file="R.csv"},
]

state_outputs = [
{plot_name="Dynamics", type="population", observation="S", line_colour="green"},
{plot_name="Dynamics", type="population", observation="E", line_colour="magenta"},
{plot_name="Dynamics", type="population", observation="I", line_colour="red"},
{plot_name="Dynamics", type="population", observation="R", line_colour="blue"}
]

plot_param_values = "true"

